name: Clojure CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
    - name: Run Clojure Format Checker
      run: lein cljfmt check
    - name: Compute test coverage
      run: lein cloverage
    - uses: actions/upload-artifact@v2
      with:
        name: Test Coverage Overview
        path: target/coverage
    - name: Check for outdated dependencies
      run: lein ancient
